apiVersion: v1
kind: Secret
metadata:
  name: {{ include "piro.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "piro.name" . }}
    helm.sh/chart: {{ include "piro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- if .Values.repositories.github }}
    checksum/checksd-config: {{ .Files.Get .Values.repositories.github.privateKeyPath | sha256sum }}
    {{- end }}
data:
{{- if .Values.repositories.github }}
  github-app.pem: {{ .Files.Get .Values.repositories.github.privateKeyPath | b64enc }}
{{- end }}
