// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PiroUIClient is the client API for PiroUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PiroUIClient interface {
	// ListJobSpecs returns a list of Job(s) that can be started through the Piro UI.
	ListJobSpecs(ctx context.Context, in *ListJobSpecsRequest, opts ...grpc.CallOption) (PiroUI_ListJobSpecsClient, error)
	// IsReadOnly returns true if the Piro UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type piroUIClient struct {
	cc grpc.ClientConnInterface
}

func NewPiroUIClient(cc grpc.ClientConnInterface) PiroUIClient {
	return &piroUIClient{cc}
}

func (c *piroUIClient) ListJobSpecs(ctx context.Context, in *ListJobSpecsRequest, opts ...grpc.CallOption) (PiroUI_ListJobSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &PiroUI_ServiceDesc.Streams[0], "/v1.PiroUI/ListJobSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &piroUIListJobSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PiroUI_ListJobSpecsClient interface {
	Recv() (*ListJobSpecsResponse, error)
	grpc.ClientStream
}

type piroUIListJobSpecsClient struct {
	grpc.ClientStream
}

func (x *piroUIListJobSpecsClient) Recv() (*ListJobSpecsResponse, error) {
	m := new(ListJobSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *piroUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.PiroUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PiroUIServer is the server API for PiroUI service.
// All implementations must embed UnimplementedPiroUIServer
// for forward compatibility
type PiroUIServer interface {
	// ListJobSpecs returns a list of Job(s) that can be started through the Piro UI.
	ListJobSpecs(*ListJobSpecsRequest, PiroUI_ListJobSpecsServer) error
	// IsReadOnly returns true if the Piro UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedPiroUIServer()
}

// UnimplementedPiroUIServer must be embedded to have forward compatible implementations.
type UnimplementedPiroUIServer struct {
}

func (UnimplementedPiroUIServer) ListJobSpecs(*ListJobSpecsRequest, PiroUI_ListJobSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListJobSpecs not implemented")
}
func (UnimplementedPiroUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedPiroUIServer) mustEmbedUnimplementedPiroUIServer() {}

// UnsafePiroUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PiroUIServer will
// result in compilation errors.
type UnsafePiroUIServer interface {
	mustEmbedUnimplementedPiroUIServer()
}

func RegisterPiroUIServer(s grpc.ServiceRegistrar, srv PiroUIServer) {
	s.RegisterService(&PiroUI_ServiceDesc, srv)
}

func _PiroUI_ListJobSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListJobSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PiroUIServer).ListJobSpecs(m, &piroUIListJobSpecsServer{stream})
}

type PiroUI_ListJobSpecsServer interface {
	Send(*ListJobSpecsResponse) error
	grpc.ServerStream
}

type piroUIListJobSpecsServer struct {
	grpc.ServerStream
}

func (x *piroUIListJobSpecsServer) Send(m *ListJobSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PiroUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PiroUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PiroUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PiroUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PiroUI_ServiceDesc is the grpc.ServiceDesc for PiroUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PiroUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.PiroUI",
	HandlerType: (*PiroUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _PiroUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListJobSpecs",
			Handler:       _PiroUI_ListJobSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "piro-ui.proto",
}
