packages:
  - name: rice
    type: generic
    srcs:
      - "migrations/*"
      - "migration.go"
    config:
      commands:
        - ["go", "mod", "init", "github.com/bhojpur/piro/pg"]
        - ["go", "get", "github.com/GeertJohan/go.rice/rice"]
        - ["sh", "-c", "$GOPATH/bin/rice embed-go"]
        - ["rm", "-rf", "migrations", "migration.go"]
        - ["go", "fmt", "./..."]
